try ssh

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -38,7 +38,13 @@ runs:
         -H "Authorization: Bearer ${{ github.token }}" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         https://api.github.com/repos/${{ github.repository }}/zipball --output zipball.zip
-        ls -l zipball.zip
+        if [ -f zipball.zip ]; then
+            echo "zipball.zip is present"
+            ls -l zipball.zip
+        else
+            echo "Error: zipball.zip is not present"
+            exit 1
+        fi
 
     # - name: Test access
     #   shell: bash
